#!/bin/sh

sfeed_update $HOME/rss/youtube/sfeedrc

export SFEED_PLUMBER=umpv
export SFEED_PLUMBER_INTERACTIVE=1
export SFEED_AUTOCMD="t"
export SFEED_URL_FILE="$HOME/rss/urls-youtube"
[ -f "$SFEED_URL_FILE" ] || touch "$SFEED_URL_FILE"
sfeed_curses $HOME/rss/youtube/feeds/*
